### ISSUE TITLE
N in PAMPAC does not allow min=0

### ISSUE THREAD

**Issue by joancf** [GateNLP/python-gatenlp#137] opened 2021-09-20 18:27 UTC
**Please give all details about your system and software used:**
- Operating System: Linux Mint 20
- Python Version: 3.8
- How was gatenlp installed: Pip install from side project  pip intstal -e ../python-gatenlp[spacy,formants]

**Describe the bug**
the pampac rule maching for N elements fails when the minimum number of elements is 0 .  I matches every char, instead of every annotation.

**To Reproduce**
```
nlp = spacy.load("en_core_web_sm")
doc=Document ("The wheel of the car was found near the restaurant of the gas station of my friend 8 ")
doc=apply_spacy(nlp,doc,  setname="Original markups")
np=AnnAt("NounChunk" )
rCK = Rule(
            Seq ( N( Seq(   np,
                            AnnAt("Token", features=dict(lemma="of"))
                         ), min=1, max=6, name="chunk" 
                  ),
                  np,
                  name="chunk"),
            AddAnn( name="chunk" , type="extendedNP")
)
outset = doc.annset("Original markups")
annSet=doc.annset("Original markups").with_type("NounChunk","Token")
Pampac(rCK, skip="one").run(doc, annSet, outset=outset)
annSet=doc.annset("Original markups").with_type("extendedNP")
for ann in annSet:
      print (ann)
```
That one gives 3 extendedNP
```
Annotation(0,12,extendedNP,features=Features({}),id=43)
Annotation(36,72,extendedNP,features=Features({}),id=44)
Annotation(54,72,extendedNP,features=Features({}),id=45)
```

while this other one : 

```
nlp = spacy.load("en_core_web_sm")
doc=Document ("The wheel of the car was found near the restaurant of the gas station of my friend 8 ")
doc=apply_spacy(nlp,doc,  setname="Original markups")
np=AnnAt("NounChunk" )
rCK = Rule(
            Seq ( N( Seq(   np,
                            AnnAt("Token", features=dict(lemma="of"))
                         ), min=0, max=6, name="chunk" 
                  ),
                  np,
                  name="chunk"),
            AddAnn( name="chunk" , type="extendedNP")
)
outset = doc.annset("Original markups")
annSet=doc.annset("Original markups").with_type("NounChunk","Token")
Pampac(rCK, skip="one").run(doc, annSet, outset=outset)
annSet=doc.annset("Original markups").with_type("extendedNP")
for ann in annSet:
      print (ann)
```
gives as result 9 extendedNP but with wrong sizes
```
Annotation(0,12,extendedNP,features=Features({}),id=43)
Annotation(11,11,extendedNP,features=Features({}),id=44)
Annotation(12,12,extendedNP,features=Features({}),id=45)
Annotation(13,13,extendedNP,features=Features({}),id=46)
Annotation(36,72,extendedNP,features=Features({}),id=47)
Annotation(54,72,extendedNP,features=Features({}),id=48)
Annotation(71,71,extendedNP,features=Features({}),id=49)
Annotation(72,72,extendedNP,features=Features({}),id=50)
Annotation(73,73,extendedNP,features=Features({}),id=51)
```

**Comment by joancf** [comment] 2021-09-20 18:34
Also select All does not seem to work.
```
rCK = Rule(
            Seq ( N( Seq(   np,
                            AnnAt("Token", features=dict(lemma="of"))
                         ), min=1, max=6, name="chunk" ,select="all"
                  ),
                  np,
                  name="chunk"),
            AddAnn( name="chunk" , type="extendedNP")
)
```
gives  
Annotation(32,72,extendedNP,features=Features({}),id=43)
Annotation(33,72,extendedNP,features=Features({}),id=44)
Annotation(34,72,extendedNP,features=Features({}),id=45)
Annotation(35,72,extendedNP,features=Features({}),id=46)
Annotation(36,72,extendedNP,features=Features({}),id=47)

while  
```
rCK = Rule(
            Seq ( N( Seq(   np,
                            AnnAt("Token", features=dict(lemma="of"))
                         ), min=1, max=6, name="chunk" 
                  ),
                  np,
                  name="chunk",select="all"),
            AddAnn( name="chunk" , type="extendedNP")
)
```
gives the error:
```
~/devel/python-gatenlp/gatenlp/pam/pampac/pampac_parsers.py in depthfirst(lvl, result)
   1412                                 tmpmatches.append(
   1413                                     dict(
-> 1414                                         span=Span(start, end),
   1415                                         location=loc,
   1416                                         name=self.name,

NameError: free variable 'start' referenced before assignment in enclosing scope
```

**Comment by johann-petrak** [comment] 2021-09-20 20:28
Thanks for that report! 
First, I apologize, I might have pushed the wrong commit on the  "main" branch, so please, could you first check out the current version? I will do all other changes on a branch so as to not mix up things.

Second, I have created a notebook for these issues here: https://nbviewer.jupyter.org/github/GateNLP/python-gatenlp/blob/918c1424039a423a3531d3a0bb232e62224868c2/debug/debug-pampac-issue137.ipynb
* I think the way how a zero iteration match is processed as the prefix of a longer match is wrong, I will look into this
* I have included something that may be a different way to achieve what you perhaps want: match a sequence which must have the nounchunk first, followed by 1 to k or 0 to k sequences of ("of" NounChunk). This seems to work (see examples 01 and 02 in the notebook)
* I have created a different issue #138 for the select="all" issue. In this example, the select="all" setting should not make a difference at all as there are no alternate parsing paths for the expression

**Comment by johann-petrak** [comment] 2021-09-21 13:33
Thinking about this again, I think the result is actually expected behaviour and not a bug: sometimes thinking about what a specific pattern *should* do can be hard to wrap one's mind around :)

In the example with min=0, we have a situation where two things are combined:
* A N() pattern with min=0 coming BEFORE something else
* the Pampac parameter skip is "one" 

But what N(min=0, max=k) mean? Where should it match in the case of n=0? Obviously not matching whatever parser is inside N counts as 0 matches. So this will match at any location where there are 0 annotations that can match the pattern inside N. 
The whole outser sequence then match at ALL positions where there are zero annotations that can match N, followed by a Noun chunk.

After the initial match at offset 0, the skip is one mode will try offset 1 next. 
The N() can match at offset 1 but the next annotation after that offset is not a NounChunk, so it will not match.
This is the case for all subsequent offsets until we are one past the last annotation before the first NounChunk, which happens at offset 11 (the Token starts at 10): at this offset, we can match 0 times the pattern in N, followed by the NounChunk, so this is a proper match. Same for offsets 12 and 13. 

Does this make sense? 

So again, I think the better solution is to come up with a pattern where we do not need 0-time matching of anything because that could really be confusing and hard to interpret correctly.

**Comment by johann-petrak** [comment] 2021-09-21 15:34
I have commited some additional changes where the example above with min=0 should give the same number of matches with the same starting offset, but proper lengths. 

I am closing this for now, please feel free to reopen or open a new issue if I have missed something or a new bug appears!

**Closed by johann-petrak** 2021-09-21 15:34 UTC
Labels: bug

**Comment by joancf** [comment] 2021-09-22 21:23
Thanks Johann,
Just a comment... do you think it would be interesting to "compile" the rule in order to generate a finite automata and then run the finite automata?

**Comment by johann-petrak** [comment] 2021-09-22 21:33
This implementation deliberately does not uses FAs but uses the parser combinators instead. What Pampac can do already would have been very hard to impossible to implement as FAs and in principle parser combinators could do even more complex things (the set of languages parsable by parser combinators includes e.g. things like recursively nested constructs, something that is not possible with NFAs). 
Implementing and optimizing an FA would also probably be even more complex than using parser combinators. 

On the other hand, if somebody wants to contribute the code to provide the same or similar functionality through an FA implementation, or prove me wrong by showing that it would be easier to do I am all for it! :)

**Comment by joancf** [comment] 2021-09-22 22:37
Johann, thanks for the offering ;-) 
Is it true that a recursive descent parser (build using functions) allows context free grammars. 
I have not check the the full list of functions available in  pampac, but and/or/N/seq.. all of them seem equivalent to RE, and I don't see how recursive  expressions could be done with them,  i can nest them but, can I perform a recursive call?, so, ie. is it possible to  define? 
```
Expr = Or (  Seq  (  Ann ("Token" , text = "(" ),  
                               Expr ,
                               Ann ("Token" , text = ")")
                            ),
                      Ann ("Token", text= "[0-9]+" )
                  )
```
equivalent to 
Epr -> ( Expr ) or Num

**Comment by johann-petrak** [comment] 2021-09-23 06:13
Yes, this is on the list of planned things but not implemented yet (like a bunch of other things like caching). 
It would need a special functional forward declaration construct (your code example would not work in Python as the "Expr"  on the right hand side is not defined or not defined correctly yet.)
