### ISSUE TITLE
Infinite pipeline loading time

### ISSUE THREAD

**Issue by robinjournet** [GateNLP/python-gatenlp#118] opened 2021-06-25 07:40 UTC
Hi everyone,

I followed instruction on how to use gate worker on this page, https://gatenlp.github.io/python-gatenlp/gateworker.

I'm currently trying before running a pipeline on some document to load a pipeline xgapp with a Jupyter notebook.

The code is the following:
```python
# Importer
from gatenlp.gateworker import GateWorker
fileName = r"C:\Users\xxxx\Documents\GitXxxxx\Enumeration\ListAPuces.xgapp"
# Boucle which takes care of everything(can also use executor for application on one corpus)
with GateWorker(start=True, auth_token="verysecretauthtoken") as gw:
    print("loading pipeline")
    pipeline = gw.worker.loadPipelineFromFile(fileName)
    print(gw.gate_version)
    print(pipeline)
```
    
   I get these results :
   ```python
Trying to start GATE Worker on port=25333 host=127.0.0.1 log=false keep=false
Process id is 7932
PythonWorkerRunner.java: starting server with 25333/127.0.0.1/verysecretauthtoken/false
loading pipeline
```

As we can see, the gate worker is finely initialized, but **the loop runs without ever printing the gate version or the pipeline object**.

What mistake did I make, or what is wrong with the module gate worker, and is there anything I need to specify in order to at least load the pipeline ?

Thank you in advance

**Comment by johann-petrak** [comment] 2021-06-25 08:03
Hi, thanks for reporting. Could you please report:
* your gatenlp version 
* your GATE version
* your Java version? 
* From the file name I assume you are trying this on Windows, is it Windows 10?

**Comment by robinjournet** [comment] 2021-06-25 08:22
Thank you for answering, here is my info:

Gatenlp version : **1.0.4**

GATE version : **9.1-SNAPSHOT**

JAVA version : **openjdk version "11.0.10" 2021-01-19
                       OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
                       OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.10+9, mixed mode)**

Python version: **3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]**

Yes I use windows 10.

Thank you

**Comment by johann-petrak** [comment] 2021-06-25 09:19
I am unable to reproduce this problem with gatenlp 1.0.4, GATE 9.1-SNAPSHOT, Python 3.7.9 and Java version openjdk 15.0.1 on Windows 10. 

I have create annie.xgapp by opening the GATE GUI, loading the ready made ANNIE application and saving it as annie.xgapp

I am using this python file:

```python
from gatenlp.gateworker import GateWorker
import gatenlp
print(f"gatenlp version {gatenlp.__version__}")
fileName = r"C:\Users\johann\tmptestgatenlp\test-load-pipeline\annie.xgapp"
gw = GateWorker(start=True, auth_token="verysecretauthtoken", gatehome=r"C:\Program Files\GATE_Developer_9.1-SNAPSHOT")
print(f"GateWorker loaded, GATE version={gw.gate_version}")
print("Loading pipeline")
pipeline = gw.worker.loadPipelineFromFile(fileName)
print(pipeline)
gw.close()
```

Could you please try and replace the two paths in the code with what applies to your machine and run this? 

I assume you can load the pipeline file without problems directly in the GATE GUI?

**Comment by robinjournet** [comment] 2021-06-25 13:49
Alright, running your solution, it would seem there are several problems(and solutions) and I think it is interesting that other users know it (maybe it is already specified in the documentation and I just haven't found it, my bad if it is so).
1) **It is impossible to load a pipeline in a Jupyter notebook**. Using the method loadPipelineFromFIle from GateWorker class would seem to be only possible from a .py file. 

I've been trying your methods on 4 different xgapp, and it worked only with one of them, and it is the one that is the biggest(most plugins, most japes, most gazetteers) which is weird. 

2) After investigating, the issue seems to be due to python Gate NLP only accepting some kind of xgapp pipeline. Indeed, after processing those 4 projects through an 'export for GATE cloud' it now works with all of them.  It might be necessary for the xgapp or the folder architecture to be specific, or something, for python-GateNLP to load it. **Running a ready-made application through an export to GATE cloud and unzipping it seems to be the solution.** 

Thank you a lot for your time and consideration

**Comment by ianroberts** [comment] 2021-06-25 14:02
> Indeed, after processing those 4 projects through an 'export for GATE cloud' it now works with all of them.

The export for GATE Cloud option does several things, firstly it gathers all the files that the pipeline depends on into folders under the location of the `xgapp` (so it isn't referring to any `../` relative paths), but secondly it caches a local copy of all the plugins that the app depends on so that the GateWorker does not have to go out to the internet to download them at runtime.  With particularly large plugins such as the `Twitter` one that download can take a while, and there's no progress bar telling you what's happening.

**Comment by johann-petrak** [comment] 2021-06-25 15:46
Thanks for the feedback and helping to figure this out! 

This looks all really weird, and it would be good to get at the bottom of it:

1. it is definitely possible to load pipelines in a Jupyter notebook. I just verified this with the code above on both Linux and Windows 10.  All documentation pages and the example code are originally written as Jupyter notebooks.  When you try to run it from within a notebook, what happens? Do you get any error messages or exceptions?
2. `gatenlp` should be able to load ANY pipeline you can load into the GATE GUI from the same local directory.
3. If a pipeline cannot be loaded, a detailed exception should be shown which includes the Java exception information from the Java side. At least if loading the same pipeline from GATE GUI also throws an exception. Basically, loading the pipeline via the GateWorker and from the GUI should show exactly the same symptoms since behind the scenes, the GateWorker simply runs the same Java method in a Java GATE environment. As @ianroberts  pointed out, the hanging may be caused by fetching plugins from the Internet taking a long time. Loading the pipeline first into the Java GATE GUI and then via the gatenlp GateWorker should make sure that the GateWorker already finds the cached plugins on your machine.

**Comment by robinjournet** [comment] 2021-06-29 15:31
Thank you for your answer.

1. It is indeed possible to load pipelines in the Jupiter notebook, and it now works on my computer.  To this day, I still haven't got any error messages for some pipelines that I tried to load. After some tests, it would seem to be due to an error of plugin. Now, GATE GUI doesn't seem to have any problems fully loading the pipeline. Nonetheless, it throws an error ('Could not reload creole directory file:/C:/Users/robin/Documents/Git/plugins/Format_SemaGraph/') but it doesn't prevent loading the pipeline or running it on any corpus/documents. However loading such pipeline with a Jupyter notebook, using gate worker, it is running indefinitely (no error messages just an executing cell forever). Loading it on a standard ".py" file throws the message "We've hit an error!" and stop the process.
2. Also, I do have 2 plugins being used in some of the pipeline I tested( precisely those that are a problem), and it would seem that what @ianroberts said to be relevant here 
3. The problem was apparently temporary, and I don't know what fixed it. Although I still have a slightly different behavior between gate worker and Gate GUI(see 1. ), I now can load any pipeline that is seemingly running on one or the other. 

Thank you for all your support and your time.

**Comment by johann-petrak** [comment] 2021-06-29 21:08
Thanks for that feedback. 
I am not sure what the "Could not reload creole directory" is and when it occurs, or how to reproduce it,  @ianroberts can you shed light on this? If I can deliberately create that error somehow I could test how the GateWorker will behave in such a case. 
In theory, Java exceptions should bubble up to Python, but maybe something is different here.

**Comment by johann-petrak** [comment] 2021-07-02 16:04
No feedback after 3 days, closing.
Feel free to reopen if there still is a problem.

**Closed by johann-petrak** 2021-07-02 16:04 UTC
